name: "gps"
driver:
  package: romea_gps_driver
  executable: tcp_client_node
  parameters:
    ip: 192.168.3.1  # no ethernet cable
    nmea_port: 1003
    rtcm_port: 1002
ntrip:
  package: ntrip_client
  executable: ntrip_ros.py
  parameters:
    host: caster.centipede.fr.disabled
    port: 2101
    username: centipede
    password: centipede
    mountpoint: MTLDR
configuration:
  type: drotek
  model: f9p
  rate: 10
  dual_antenna: false  # only 1 antenna
geometry:
  parent_link: "base_link"
  xyz: [-0.1125, -0.3, 1.11]  # calibrated by Guillaume
records:
  nmea_sentence: true
  gps_fix: false
  vel: false
