name: imu
driver:
  package: xsens_driver
  executable: mtnode.py
  parameters:
    device: /dev/imu
    baudrate: 115200
configuration:
  type: xsens
  model: mti
  rate: 100
geometry:
  parent_link: base_link
  xyz: [0.0, 0.0, 0.0]
  rpy: [0.0, 0.0, 90.0]  # x axis directed to the left of the robot
