x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  x11-base: &x11-base
    extends:
      file: ../../docker/common.yaml
      service: x11_base
    volumes:
      - ./config:/config


services:
  bash:
    <<: [*x11-base]
    profiles: [optional]
    command: bash

  robot:
    <<: [*x11]
    command: >-
      ros2 launch tirrex_demo robot.launch.py
        demo_config_directory:=/config
        robot_configuration_directory:=/config/pom
        robot_namespace:=pom
        mode:=live

  path_following:
    <<: [*x11]
    depends_on: [robot]
    command: >-
      ros2 launch tirrex_path_following path_following.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/robot
        launch_robot:=false
        robot:=adap2e
        path:=cezeaux_line.traj
        mode:=live

  path_recorder:
    <<: [*x11]
    profiles: [optional]
    depends_on: [robot]
    command: >-
      ros2 launch tirrex_path_following path_recorder.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/robot
        launch_robot:=false
        robot:=adap2e
        mode:=live
        path:=/config/paths/recorded.traj

  rviz:
    <<: [*x11]
    profiles: [optional]
    depends_on: [robot]
    command: rviz2 -d /config/config.rviz
