name: gps
driver:
  package: romea_gps_driver
  executable: tcp_client_node
  parameters:
    ip: 192.168.0.50
    nmea_port: 1003
    rtcm_port: 1001
ntrip:
  package: ntrip_client
  executable: ntrip_ros.py
  parameters:
    host: crtk.net
    port: 2101
    username: centipede
    password: centipede
    mountpoint: MTLDR
configuration:
  type: drotek
  model: f9p
  rate: 10
  dual_antenna: true
geometry:
  parent_link: base_link
  xyz: [-0.36, 0.36, 1.0]
records:
  nmea_sentence: true
  fix: true
  vel: false
