x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  base: &base
    extends:
      file: ../../docker/common.yaml
      service: x11_robot
    volumes:
      - ./config:/config
    environment:
      - CONFIG_DIR=/config
      - ROBOT_CONFIG_DIR=/config/robot
      - DEMO_MODE=live
      - DEMO_NAME=montoldre_ceol
      - ROBOT_NAMESPACE=robot
      - ROS_LOG_DIR=data/montoldre_ceol/log

services:
  bash:
    <<: [*base]
    profiles: [optional]
    command: bash

  ceol_test:
    <<: [*base]
    profiles: [optional]
    command: 'ros2 launch ceol_bringup ceol_test.launch.py mode:=live'

  zenoh:
    <<: [*base]
    command: zenoh-bridge-ros2dds -c /config/zenoh_bridge.json5

  robot:
    <<: [*base]
    depends_on: [zenoh]
    command: >-
      ros2 launch tirrex_demo core.launch.py
        demo_config_directory:=$$CONFIG_DIR
        robot_config_directory:=$$ROBOT_CONFIG_DIR
        robot_namespace:=$$ROBOT_NAMESPACE
        mode:=$$DEMO_MODE

  localisation:  # compute absolute localization using GNSS, IMU and odometry measurements
    <<: [*base]
    depends_on: [robot]
    command: >-
      ros2 launch tirrex_demo robot_localisation.launch.py
        demo_config_directory:=$$CONFIG_DIR
        robot_config_directory:=$$ROBOT_CONFIG_DIR
        robot_namespace:=$$ROBOT_NAMESPACE
        mode:=$$DEMO_MODE

  path_following:  # control the robot to follow the specified trajectory file
    <<: [*base]
    depends_on: [localisation]
    command: >-
      ros2 launch tirrex_demo robot_path_following.launch.py
        demo_config_directory:=$$CONFIG_DIR
        robot_config_directory:=$$ROBOT_CONFIG_DIR
        robot_namespace:=$$ROBOT_NAMESPACE
        mode:=$$DEMO_MODE
        trajectory_filename:=loop1.traj

  path_recorder:  # record a trajectory file from the current localization
    <<: [*base]
    depends_on: [localisation]
    profiles: [optional]
    command: >-
      ros2 launch tirrex_demo robot_path_recorder.launch.py
        demo_config_directory:=$$CONFIG_DIR
        robot_config_directory:=$$ROBOT_CONFIG_DIR
        robot_namespace:=$$ROBOT_NAMESPACE
        mode:=$$DEMO_MODE
        trajectory_filename:=/config/paths/recorded.traj

  rviz:  # start evaluation nodes and publish information for rviz
    <<: [*base]
    profiles: [optional]
    command: rviz2 -d /config/default.rviz

  record:
    <<: [*base]
    depends_on: [robot]
    command: >-
      ros2 launch tirrex_demo record.launch.py
        demo_config_directory:=$$CONFIG_DIR
        robot_config_directory:=$$ROBOT_CONFIG_DIR
        robot_namespace:=$$ROBOT_NAMESPACE
        mode:=$$DEMO_MODE
        demo:=$$DEMO_NAME
