x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  base: &base
    extends:
      file: ../../docker/common.yaml
      service: x11_base
    volumes:
      - ./config:/config
    environment:
      - CONFIG_DIR=/config
      - ROBOT_CONFIG_DIR=/config/robot
      - DEMO_MODE=simulation_gazebo_classic
      - ROBOT_NAMESPACE=robot

services:
  bash:
    <<: [*base]
    profiles: [optional]
    command: bash

  simulator:  # start the simulator and spawn the robot
    <<: [*base]
    command: >-
      ros2 launch tirrex_demo core.launch.py
        demo_config_directory:=$$CONFIG_DIR
        robot_config_directory:=$$ROBOT_CONFIG_DIR
        mode:=$$DEMO_MODE
        robot_namespace:=$$ROBOT_NAMESPACE

  localisation:  # compute absolute localization using GNSS, IMU and odometry measurements
    <<: [*base]
    depends_on: [simulator]
    command: >-
      ros2 launch tirrex_demo robot_localisation.launch.py
        demo_config_directory:=$$CONFIG_DIR
        robot_config_directory:=$$ROBOT_CONFIG_DIR
        mode:=$$DEMO_MODE
        robot_namespace:=$$ROBOT_NAMESPACE

  path_following:  # control the robot to follow the specified trajectory file
    <<: [*base]
    depends_on: [localisation]
    command: >-
      ros2 launch tirrex_demo robot_path_following.launch.py
        demo_config_directory:=$$CONFIG_DIR
        robot_config_directory:=$$ROBOT_CONFIG_DIR
        mode:=$$DEMO_MODE
        robot_namespace:=$$ROBOT_NAMESPACE
        trajectory_filename:=test01_annotated.traj

  path_recorder:  # record a trajectory file from the current localization
    <<: [*base]
    depends_on: [localisation]
    profiles: [optional]
    command: >-
      ros2 launch tirrex_demo robot_path_recorder.launch.py
        demo_config_directory:=$$CONFIG_DIR
        robot_config_directory:=$$ROBOT_CONFIG_DIR
        mode:=$$DEMO_MODE
        robot_namespace:=$$ROBOT_NAMESPACE
        trajectory_filename:=/config/paths/recorded.traj

  rviz:  # start evaluation nodes and publish information for rviz
    <<: [*base]
    command: rviz2 -d /config/default.rviz
