name: lidar_back
driver:
  package: sick_scan_xd
  executable: sick_generic_caller
  parameters:
    hostname: 192.168.0.22
    port: "2112"
configuration:
  type: sick
  model: lms151
  rate: 50
  resolution: 0.5
geometry:
  parent_link: base_link
  xyz: [-0.732, 0.0, 0.34]
  rpy: [0.0, 44.2, 180.0]
records:
  scan: true
  cloud: false
