name: "gps"
driver:
  package: "romea_gps_driver"
  executable: "serial_node"
  parameters:
    device: "/dev/ttyACM0"
    baudrate: 115200
ntrip:
  package: ntrip_client
  executable: ntrip_ros.py
  parameters:
    host: caster.centipede.fr
    port: 2101
    username: centipede
    password: centipede
    mountpoint: MAGC
configuration:
  type: drotek
  model: f9p
  rate: 10
  dual_antenna: true
geometry:
  parent_link: "base_link"
  xyz: [-0.40, 0.0, 1.5]
