sampling_period: 0.1

# control setpoint
setpoint:
  desired_linear_speed: 1.0
  desired_lateral_deviation: 0.0
  desired_course_deviation: 0.0

# configuration of longitudinal control
longitudinal_control:
  minimal_linear_speed: 0.3

# configuration for classic and predictive lateral control laws
lateral_control:
  selected: back_stepping

  back_stepping:
    gains:
      kp: -1.5
      kd: -3.0
    maximal_omega_d: 0.5

  skid_sliding:
    gains:
      lateral_kp: -1.5
      course_kp: -3.0

# other options
stop_at_the_end: false
autoconfigure: true
autostart: true

# configuration for cmd_mux auto connection
cmd_output:
  message_type: romea_mobile_base_msgs/SkidSteeringCommand
  priority: 10 # if -1, disable registering to cmd_mux
  rate: 10.

debug: true
