name: "keyboard"
driver:
  package: "pynput_teleop"
  executable: "pynput_joy"
  parameters:
    up_down:
      increment: 0.1
    left_right:
      value_max: 0.3
    publish:
      rate: 10
configuration:
  type: keyboard
records:
  joy: true
