name: lidar_front
driver:
  package: sick_scan_xd
  executable: sick_generic_caller
  parameters:
    hostname: 192.168.0.21
    port: "2112"
configuration:
  type: sick
  model: lms151
  rate: 50
  resolution: 0.5
geometry:
  parent_link: base_link
  xyz: [2.5, 0.0, 0.388]
  rpy: [0.0, 46.8, 0.0]
records:
  scan: true
  cloud: false
