sampling_period: 0.1

# control setpoint
setpoint:
  desired_linear_speed: 1.0
  desired_lateral_deviation: 0.0
  desired_course_deviation: 0.0

# configuration of longitudinal control
longitudinal_control:
  minimal_linear_speed: 0.3

# configuration for classic and predictive lateral control laws
lateral_control:
  selected: skid_backstepping

  back_stepping:
    gains:
      kp: -1.5
      kd: -3.0
    maximal_omega_d: 0.5

  skid_backstepping:
    gains:
      lateral_kp: -1.0  # (unit: 1/m) negative, proportional, spatial diff. eq.
      course_kp: -2.0   # (unit: 1/s) negative, proportional, temporal diff. eq., < lateral_kp
    maximal_target_course_deg: 45.  # control the angle to reach the desired lateral deviation

# other options
stop_at_the_end: false
autoconfigure: true
autostart: true

# configuration for cmd_mux auto connection
cmd_output:
  message_type: romea_mobile_base_msgs/SkidSteeringCommand
  priority: -1 # if -1, disable registering to cmd_mux
  rate: 10.

debug: true
