x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  x11: &x11
    extends:
      file: ../../docker/common.yaml
      service: x11_robot
    environment:
      - ROS_DOMAIN_ID=28
    volumes:
      - ./config:/config

services:
  bash:
    <<: [*x11]
    profiles: [optional]
    command: 'bash --rcfile /etc/bash.bashrc'

  robot:
    <<: [*x11]
    command: >-
      ros2 launch tirrex_demo robot.launch.py
        demo_config_directory:=/config
        robot_configuration_directory:=/config/robot
        robot_namespace:=adap2e
        mode:=live

  path_following:
    <<: [*x11]
    command: >-
      ros2 launch tirrex_path_following path_following.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/robot
        launch_robot:=false
        robot:=adap2e
        path:=cezeaux_line.traj
        mode:=live

  path_recorder:
    <<: [*x11]
    profiles: [optional]
    command: >-
      ros2 launch tirrex_path_following path_recorder.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/robot
        launch_robot:=false
        robot:=adap2e
        mode:=live
        path:=/config/paths/recorded.traj
