x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  base: &base
    extends:
      file: ../../docker/common.yaml
      service: x11_robot
    volumes:
      - ./config:/config
    environment:
      - ROS_LOG_DIR=data/adap2e/log

services:
  bash:
    <<: [*base]
    profiles: [optional]
    command: 'bash --rcfile /etc/bash.bashrc'

  robot:
    <<: [*base]
    command: >-
      ros2 launch tirrex_demo core.launch.py
        demo_config_directory:=/config
        robot_configuration_directory:=/config/robot
        robot_namespace:=robot
        mode:=live

  localisation:  # compute absolute localization using GNSS, IMU and odometry measurements
    <<: [*base]
    depends_on: [robot]
    command: >-
      ros2 launch tirrex_demo robot_localisation.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/robot
        mode:=live
        robot_namespace:=robot

  path_following:  # control the robot to follow the specified trajectory file
    <<: [*base]
    depends_on: [localisation]
    command: >-
      ros2 launch tirrex_demo robot_path_following.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/robot
        mode:=live
        robot_namespace:=robot
        trajectory_filename:=test01.traj

  path_recorder:  # record a trajectory file from the current localization
    <<: [*base]
    depends_on: [localisation]
    profiles: [optional]
    command: >-
      ros2 launch tirrex_demo robot_path_recorder.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/robot
        mode:=live
        robot_namespace:=robot
        trajectory_filename:=/config/paths/recorded.traj

  rviz:
    <<: [*base]
    profiles: [optional]
    depends_on: [robot]
    command: rviz2 -d /config/config.rviz

  record:
    <<: [*base]
    depends_on: [robot]
    profiles: [optional]
    command: /config/record.sh
