inc_trans: 0.05
inc_thetaRotate: 0.5
scope_mini: 1.0
scope_maxi: 50.0
angle_limit_rotate: 90.0
offset_scan: 45.0
alpha_detection: 10.0
radius: 1.0
snake_length_max_left: 10.0
snake_length_max_right: 10.0
z_layers: [0.2,0.4,0.6]
visualization_lifetime: 0.01