autostart: true
debug: false

desired_linear_speed: 0.8
desired_lateral_deviation: -1.05

gains:
  kp: -1.0
  ki: 0.0
  kd: 1.0
  kdd: 1.0

#configuration for cmd_mux auto connection
cmd_output:
  message_type: romea_mobile_base_msgs/OneAxleSteeringCommand
  priority: 10
  rate: 10.
