sampling_period: 0.1

# control setpoint
setpoint:
  desired_linear_speed: 0.4
  desired_lateral_deviation: 0.0
  desired_course_deviation: 0.0

stop_at_the_end: true
enable_joystick: true
autoconfigure: true
autostart: false
debug: true

# configuration of longitudinal control
longitudinal_control:
  minimal_linear_speed: 0.3

lateral_control:
  # selected: back_stepping
  selected: skid_backstepping

  back_stepping:
    gains:
      kp: -1.5
      kd: -3.0
    maximal_omega_d: 0.5

  skid_backstepping:
    gains:
      lateral_kp: -1.0  # (unit: 1/m) negative, proportional, spatial diff. eq.
      course_kp: -2.0   # (unit: 1/s) negative, proportional, temporal diff. eq., < lateral_kp
    maximal_target_course_deg: 45.  # control the angle to reach the desired lateral deviation

sliding_observer:
  # selected: none
  # selected: picard_skid_backstepping
  selected: picard_skid_lyapunov

  picard_skid_backstepping: # values are taken from the the Guillaume Picard PhD
    gains:
      lateral_kp: -6.0
      course_kp: -6.0
      longitudinal_kp: -8.5
      longitudinal_ki: 0.0  # integral
    filter_weights:  # the following variable are smoothed using a 1st order Butterworth filter
      slip_angle: 0.9
      linear_speed_disturb: 0.9
      angular_speed_disturb: 0.8

  picard_skid_lyapunov: # values are taken from the the Guillaume Picard PhD
    gains:
      position_x_kp: -5.0
      position_x_ki: 0.0  # integral
      position_y_kp: -5.0
      course_kp: -5.0
      slip_angle_kp: -3.0
      linear_speed_disturb_kp: -3.0
      angular_speed_disturb_kp: -3.0

# configuration for cmd_mux auto connection
cmd_output:
  message_type: romea_mobile_base_msgs/SkidSteeringCommand
  priority: 10 # if -1, disable registering to cmd_mux
  rate: 10.

debug: true
