sampling_period: 0.1

# control setpoint
setpoint:
  desired_linear_speed: 0.5
  desired_lateral_deviation: 0.0
  desired_course_deviation: 0.0

# configuration of longitudinal control
longitudinal_control:
  minimal_linear_speed: 0.3

# configuration for classic and predictive lateral control laws
lateral_control:
  selected: back_stepping

  # back_stepping gains:
  #   - kp: inverse of the distance to converge to the traj for the lateral dev (unit: 1/m)
  #         For example, if kp = 0.5, the robot converge in 3 * 1 / 0.5 = 6 meters
  #   - kd: inverse of the time to converge to the traj for the angular dev (unit: 1/s)
  back_stepping:
    gains:
      kp: -0.7
      kd: -1.2
    maximal_omega_d: 0.5


# other options
stop_at_the_end: false # not implemented
enable_joystick: false
autoconfigure: true
autostart: true
debug: true

# configuration for cmd_mux auto connection
cmd_output:
  message_type: romea_mobile_base_msgs/SkidSteeringCommand
  priority: -1 # if -1, disable registering to cmd_mux
  rate: 10.

debug: true
