#!/bin/bash

set -e
cd "$(dirname -- "${BASH_SOURCE[0]}")/.."

# only add non-existing variables in '.env' file
add_variable_to_env_file() {
    if ! grep -q "$1=" .env 2>/dev/null ; then
        echo "  - Add $1=$2 to .env"
        echo "$1=$2" >>.env
    fi
}

initialize_env_file() {
    echo 'Initialize ".env" file'
    add_variable_to_env_file UID "$(id -u)"
    add_variable_to_env_file GID "$(id -g)"
    add_variable_to_env_file USER "$(whoami)"
    add_variable_to_env_file WORKSPACE "$(pwd)"
}

# Create files and directories that are binded by docker services.
# If these files does not exist, the docker will not start because the auto creation is disabled.
# This prevents docker from creating them using root user.
create_binded_files() {
  mkdir -p "${HOME}/.gazebo"
  mkdir -p "${HOME}/.ros"
  mkdir -p "${HOME}/.config/ros.org"
  touch -a "${HOME}/.bash_history"
  touch -a "${HOME}/.Xauthority"  # used to open GUI by ssh
}

initialize_env_file
create_binded_files
