#!/bin/bash
set -e
models_file='fira_tirrex_models.zip'

cd "$(dirname -- "${BASH_SOURCE[0]}")/.."
echo 'Import packages'
vcs import -w6 <docker/tirrex.repos

echo 'Import gazebo models'
mkdir -p gazebo
wget -O "$models_file" \
  "https://nextcloud.inrae.fr/s/4PRo8ebgiLyf788/download?path=%2F&files=$models_file"
unzip "$models_file" -d gazebo
rm "$models_file"

echo 'Installation completed successfully'
