x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  base: &base
    extends:
      file: ../../../docker/common.yaml
      service: x11_robot
    volumes:
      - ../config:/config
    environment:
      - ROS_DOMAIN_ID=3

services:
  bash:
    <<: [*base]
    profiles: [optional]
    command: bash

  zenoh:
    <<: [*base]
    command: zenoh-bridge-ros2dds -c /config/zenoh_bridge.json5

  robot:
    <<: [*base]
    depends_on: [zenoh]
    command: >-
      ros2 launch tirrex_demo core.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/ceol
        robot_namespace:=follower
        mode:=live

  algos:  # start algos of the follower robot
    <<: [*base]
    depends_on: [robot]
    command: >-
      ros2 launch tirrex_platoon follower.launch.py
        demo_config_directory:=/config
        mode:=live
        demo:=fira_coop_follower
        robot_namespace:=follower
        next_robot_namespace:=leader
        robot:=ceol
        launch_robot:=false
        record:=false
        path:=mg_ceol3_line.traj

  switcher:  # state machine to switch between behaviors
    <<: [*base]
    depends_on: [algos]
    command: >-
      ros2 launch romea_control_switcher switcher.launch.py
        mode:=live
        config_file:=/config/ceol/control_switcher.yaml
        robot_namespace:=follower

  rviz:  # start evaluation nodes and publish information for rviz
    <<: [*base]
    command: rviz2 -d /config/default.rviz

  record:
    <<: [*base]
    depends_on: [algos]
    profiles: [optional]
    command: >-
      ros2 launch tirrex_demo record.launch.py
        demo_config_directory:=/config
        robot_config_directory:=/config/ceol
        mode:=live
        demo:=fira_coop_follower_record
        robot_namespace:=follower
