name: "lidar3d"
driver:
  package: "ouster_ros"
  executable: 
  parameters:
    hostname: "192.168.1.112"
    port: 2112
configuration:
  type: ouster
  model: os1_32
  rate: 10
  resolution: 0.17578125
geometry:
  parent_link: "base_link"
  xyz: [2.50, 0.0, 0.58]
  rpy: [0.0, 0.0, 0.0]
records:
  scan: true
  cloud: false
