name: implement
control:
  controller_manager:
    update_rate: 10
    configuration:
      pkg: romea_implement_bringup
      file: config/hitch_controller_manager.yaml
  controllers:
    selected: [position_controller]
    configuration:
      pkg: romea_implement_bringup
      file: config/hitch_controllers.yaml
configuration:
  type: hitch
  model: hoe
geometry:
  parent_link: "base_link"
  xyz: [-0.7, 0.0, 0.8]
  rpy: [0.0, 0.0, 0.0]
records:
  joint_states: true
